### ISSUE TITLE
Can't build PKCS11_Connector & PKCS11_Installer

### ISSUE THREAD

**Issue by bhardwahnitish19** [Gradiant/BlackICE_Connect#1]
I am trying to setup BlackICE to use it's PKCS11 extension capability. The OS that I am using is Ubuntu and I have already installed all the required linux dependencies which are mentioned [here](https://github.com/Gradiant/BlackICE_Connect/blob/master/Building_Linux_dependencies.md).

I got error while building _PKCS11_Connector & PKCS11_Installer_. 

**Error while building _PKCS11_Connector_:**

> dev-machine@Dev-Machine:~/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector$ ./linux-compile.sh
> Selected Debug (default) since no option were specified (use either -d or -r)
> Creating Makefile in /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build/
> Compiling in Debug mode
> Running cmake from /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build
> Build configuration: linux-64-debug
> Libraries path: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs
> libcurl used: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/libcurl/debug/x64
> OpenSSL used: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/openssl/debug/x64
> zLib used: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/zlib/release/x64/
> Source code root: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build
> /usr/bin/cmake -H/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector -B/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/bin/cmake -E cmake_progress_start /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build/CMakeFiles /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build/CMakeFiles/progress.marks
> make -f CMakeFiles/Makefile2 all
> make[1]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> make -f CMakeFiles/BlackICEConnect_x64.dir/build.make CMakeFiles/BlackICEConnect_x64.dir/depend
> make[2]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> cd /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build/CMakeFiles/BlackICEConnect_x64.dir/DependInfo.cmake --color=
> make[2]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> make -f CMakeFiles/BlackICEConnect_x64.dir/build.make CMakeFiles/BlackICEConnect_x64.dir/build
> make[2]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> [  7%] Building C object CMakeFiles/BlackICEConnect_x64.dir/src/cryptokiTypes.c.o
> /usr/bin/cc -DBlackICEConnect_x64_EXPORTS -DPKCS11 -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/libcurl/debug/x64/include/curl -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/openssl/debug/x64/include -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/zlib/release/x64/include -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../Modules/AKV_Module -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../Modules/Common_Module -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/cryptoki -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/Helpers -I/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../Modules/Common_Module/src  -Wimplicit-function-declaration -Wstrict-prototypes -Wmissing-prototypes -pedantic -Wfatal-errors -Wall -fstack-protector-all -Wl,-z,noexecstack  -Wimplicit-function-declaration -Wstrict-prototypes -Wmissing-prototypes -pedantic -Wfatal-errors -Wall -fstack-protector-all -Wl,-z,noexecstack -g3 -ggdb -O0 -rdynamic -fPIC   -o CMakeFiles/BlackICEConnect_x64.dir/src/cryptokiTypes.c.o   -c /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/cryptokiTypes.c
> In file included from /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/cryptoki.h:64:0,
>                  from /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/cryptokiTypes.h:15,
>                  from /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/src/cryptokiTypes.c:13:
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../Modules/AKV_Module/src/clientRest.h:16:10: fatal error: curl.h: No such file or directory
>  #include <curl.h>
>           ^~~~~~~~
> compilation terminated.
> CMakeFiles/BlackICEConnect_x64.dir/build.make:65: recipe for target 'CMakeFiles/BlackICEConnect_x64.dir/src/cryptokiTypes.c.o' failed
> make[2]: *** [CMakeFiles/BlackICEConnect_x64.dir/src/cryptokiTypes.c.o] Error 1
> make[2]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/BlackICEConnect_x64.dir/all' failed
> make[1]: *** [CMakeFiles/BlackICEConnect_x64.dir/all] Error 2
> make[1]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/linux-build'
> Makefile:86: recipe for target 'all' failed
> make: *** [all] Error 2
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector
> 

**Error while building _PKCS11_Installer_:**

> dev-machine@Dev-Machine:~/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup$ ./linux-compile.sh
> Creating Makefile in /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../linux-build
> Compiling in debug mode
> Running cmake from /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build
> Build configuration: linux-64-debug
> Build name: GradiantEncryptConfig_debug_x64
> Linked m (math lib)
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build
> /usr/bin/cmake -H/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer -B/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/bin/cmake -E cmake_progress_start /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build/CMakeFiles /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build/CMakeFiles/progress.marks
> make -f CMakeFiles/Makefile2 all
> make[1]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> make -f CMakeFiles/GradiantEncryptConfig_debug_x64.dir/build.make CMakeFiles/GradiantEncryptConfig_debug_x64.dir/depend
> make[2]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> cd /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build/CMakeFiles/GradiantEncryptConfig_debug_x64.dir/DependInfo.cmake --color=
> make[2]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> make -f CMakeFiles/GradiantEncryptConfig_debug_x64.dir/build.make CMakeFiles/GradiantEncryptConfig_debug_x64.dir/build
> make[2]: Entering directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> make[2]: Nothing to be done for 'CMakeFiles/GradiantEncryptConfig_debug_x64.dir/build'.
> make[2]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> [100%] Built target GradiantEncryptConfig_debug_x64
> make[1]: Leaving directory '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build'
> /usr/bin/cmake -E cmake_progress_start /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-build/CMakeFiles 0
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup
> cp: cannot stat '/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../../PKCS11_Connector/bin/linux-debug/x64/libBlackICEConnect_x64.so': No such file or directory
> tar: Removing leading `/home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../' from member names
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../GradiantBlackIceConnect_debug_x64/BlackICEconnect_template.cnf
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../GradiantBlackIceConnect_debug_x64/GradiantBlackIceConnect_debug_x64.tar.gz
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../GradiantBlackIceConnect_debug_x64/GradiantEncryptConfig_debug_x64
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../GradiantBlackIceConnect_debug_x64/README.txt
> /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Installer/linux-setup/../GradiantBlackIceConnect_debug_x64/setup.sh

Am I missing some required steps?

**Comment by gbalsa** [comment]
Hello @bhardwahnitish19 

That's strange, if you have built all the dependencies as it is stated in the documentation the build script should work. Could you show me the content of the directory /home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/libcurl/debug/x64/include/curl

**Comment by bhardwahnitish19** [comment]
Hi @gbalsa,
_home/dev-machine/BlackICE_Connect/BIC_PKCS11/PKCS11_Connector/../../libs/linux/libcurl/debug/x64_ doesn't have any include directory.

**Comment by gbalsa** [comment]
Hi again,

Did you follow the exact steps [here](https://github.com/Gradiant/BlackICE_Connect/blob/master/Building_Linux_dependencies.md)? Specially the configure of libcurl with the parameter:

`--prefix=<project_dir>/libs/linux/libcurl/debug/x64`

In you case <project_dir> is:

`/home/dev-machine/BlackICE_Connect`

And after compiling the library you need to do run:

`make install`

In order to have the library copied to the needed location.

You need to do that for the three libraries, zlib, openssl and libcurl.

Please, let me now if this solves the issue.

**Comment by bhardwahnitish19** [comment]
Thanks for the details. There isn't anything to be resolved at the moment. Closing the issue.
